# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: true   # to let apt-get install LAPACK/BLAS for us

# Choose a lightweight base image; we provide our own build tools.
language: c

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

# The different configurations we want to test. We have BUILD=cabal which uses
# cabal-install, and BUILD=stack which uses Stack. More documentation on each
# of those below.
#
# We set the compiler values here to tell Travis to use a different
# cache file per set of arguments.
#
# If you need to have different apt packages for each combination in the
# matrix, you can use a line such as:

matrix:
  include:
  - env: ARGS="" GHCVER=7.10.3 CABALVER=1.22 ALEXVER=3.1.7 HAPPYVER=1.19.5

    compiler: ": #stack default"
    addons: {apt: {packages: [ghc-7.10.3], sources: [hvr-ghc]}}

# # Nightly builds are allowed to fail
# - env: ARGS="--resolver nightly"
#   compiler: ": #stack nightly"
#   addons: {apt: {packages: [libgmp,libgmp-dev]}}

# allow_failures:
# - env: ARGS="--resolver nightly"

before_install:
# Using compiler above sets CC to an invalid value, so unset it
- sudo apt-get -qq update
- sudo apt-get install -y libblas-dev liblapack-dev
- unset CC
- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$HOME/.cabal/bin:$PATH
- mkdir -p ~/.local/bin
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar -xzO --wildcards '*/stack' > ~/.local/bin/stack
- chmod a+x ~/.local/bin/stack
- stack setup
- cd ..
- stack install weeder
- stack install hlint
- cd -

install:
- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
- if [ -f configure.ac ]; then autoreconf -i; fi
- |
  set -ex
  stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies
  set +ex
script:
- |
  set -ex
  stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
  # hlint ./src/
  # weeder
  set +ex

